controller_list:
  - name: widowx_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - gripper_prismatic_joint_1
  - name: gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - gripper_prismatic_joint_1