port: /dev/ttyUSB0
read_rate: 20
write_rate: 20
joints: {
    joint_1: {id: 1, ticks: 4096, range: 360.0, max_speed: 100.0},
    joint_2: {id: 2, ticks: 4096, range: 360.0, min_angle: -90.0, max_angle: 90.0, max_speed: 100.0},
    joint_3: {id: 3, ticks: 4096, range: 360.0, max_speed: 100.0, invert: true},
    joint_4: {id: 4, ticks: 4096, range: 360.0, min_angle: -90.0, max_angle: 90.0, max_speed: 100.0, invert: true}
}
controllers: {
    widowx_arm_controller: {type: follow_controller, joints: [joint_1, joint_2, joint_3, joint_4], rate: 35,
                            index: 0, action_ns: 'follow_joint_trajectory'},
}
